import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getCurrentUser } from "@/lib/dev-user";
import { Prisma } from "@prisma/client";
import { alertStatusSchema, alertUpdateSchema } from "@/lib/validation";
type Context = { params: Promise<{ id: string }> };
const invalidId = (id: string) => !id || id.length > 64;
export async function GET(_: Request, { params }: Context) { try { const { id } = await params; if (invalidId(id)) return NextResponse.json({ error: "ID de alerta inválido" }, { status: 400 }); const user = await getCurrentUser(); const alert = await prisma.alert.findFirst({ where: { id, userId: user.id }, include: { offers: true, searches: true } }); return alert ? NextResponse.json(alert) : NextResponse.json({ error: "Alerta não encontrado" }, { status: 404 }); } catch (error) { console.error("Falha ao consultar alerta", error); return NextResponse.json({ error: "Não foi possível consultar o alerta" }, { status: 500 }); } }
async function ownedAlert(id: string, userId: string) { return prisma.alert.findFirst({ where: { id, userId } }); }
export async function PATCH(request: Request, { params }: Context) { try { const { id } = await params; if (invalidId(id)) return NextResponse.json({ error: "ID de alerta inválido" }, { status: 400 }); const user = await getCurrentUser(); if (!await ownedAlert(id, user.id)) return NextResponse.json({ error: "Alerta não encontrado" }, { status: 404 }); const body = await request.json(); if ("status" in body) { const status = alertStatusSchema.safeParse(body); if (!status.success) return NextResponse.json({ error: status.error.flatten() }, { status: 400 }); return NextResponse.json(await prisma.alert.update({ where: { id }, data: { status: status.data.status } })); } const parsed = alertUpdateSchema.safeParse(body); if (!parsed.success || Object.keys(parsed.data).length === 0) return NextResponse.json({ error: parsed.success ? "Nenhum campo para atualizar" : parsed.error.flatten() }, { status: 400 }); return NextResponse.json(await prisma.alert.update({ where: { id }, data: parsed.data })); } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError) return NextResponse.json({ error: "Alerta não encontrado" }, { status: 404 }); console.error("Falha ao atualizar alerta", error); return NextResponse.json({ error: "Não foi possível atualizar o alerta" }, { status: 500 }); } }
export async function DELETE(_: Request, { params }: Context) { try { const { id } = await params; if (invalidId(id)) return NextResponse.json({ error: "ID de alerta inválido" }, { status: 400 }); const user = await getCurrentUser(); if (!await ownedAlert(id, user.id)) return NextResponse.json({ error: "Alerta não encontrado" }, { status: 404 }); await prisma.alert.delete({ where: { id } }); return new NextResponse(null, { status: 204 }); } catch (error) { console.error("Falha ao excluir alerta", error); return NextResponse.json({ error: "Não foi possível excluir o alerta" }, { status: 500 }); } }
